author: Agnate
database: false
description: RepairDispenser uses a Dispenser and raw material to repair a tool.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: ca.agnate.RepairDispenser.RepairDispenser
name: RepairDispenser
startup: postworld
version: 0.1.0
permissions:
    repairdispenser.norepair:
        description: Disables the user from repairing an item via the RepairDispenser.
        default: false